name: get_localekeys
description: Get Localekeys
version: 0.0.2
author: Khaydarov Abdulaminkhon

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1
  path: ^1.8.0
  pretty_json: ^2.0.0

